elg: Fix mising NULL compile failure
On GCC8 egl fails to compile with this error:
  error: 'NULL' undeclared (first use in this function)

As NULL is declared in stddef.h add it as an include to fix the build
failure.

Signed-off-by: Alistair Francis <alistair@alistair23.me>